Global:
  use_gpu: true
  epoch_num: 50
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: /home/temp-user/workspace/plate-recognition-low-resolution/weights/finetuned/sr/gestalt_plate/
  save_epoch_step: 5
  eval_batch_step: [0, 400]
  cal_metric_during_train: False
  pretrained_model: /home/temp-user/workspace/plate-recognition-low-resolution/weights/pretrained/sr/sr_tsrn_transformer_strock_train/best_accuracy_fixed
  checkpoints: null # Bắt đầu fine-tune từ pre-train
  save_inference_dir: /home/temp-user/workspace/plate-recognition-low-resolution/output/inference/sr_gestalt
  use_visualdl: False
  infer_img: null
  # AMP settings for VRAM reduction and speed
  use_amp: True
  amp_level: O2
  amp_dtype: float16
  scale_loss: 1024.0
  use_dynamic_loss_scaling: True
  character_dict_path: /home/temp-user/workspace/plate-recognition-low-resolution/data/english_decomposition.txt
  max_text_length: 100
  infer_mode: False
  use_space_char: False
  save_res_path: /home/temp-user/workspace/plate-recognition-low-resolution/output/sr/predicts_gestalt.txt

Optimizer:
  name: Adam
  beta1: 0.5
  beta2: 0.999
  clip_norm: 0.25
  lr:
    learning_rate: 0.0001

Architecture:
  model_type: sr
  algorithm: Gestalt
  Transform:
    name: TSRN
    STN: True
    infer_mode: False
    width: 320
    height: 48
    scale_factor: 1

Loss:
  name: StrokeFocusLoss
  character_dict_path: /home/temp-user/workspace/plate-recognition-low-resolution/data/english_decomposition.txt

PostProcess:
  name: None

Metric:
  name: SRMetric
  main_indicator: all

Train:
  dataset:
    name: LMDBDataSetSR
    data_dir: /home/temp-user/workspace/plate-recognition-low-resolution/data/lmdb_sr/train_lmdb
    transforms:
      - SRResize:
          imgH: 48
          imgW: 320
          down_sample_scale: 1
      - SRLabelEncode:
          character_dict_path: /home/temp-user/workspace/plate-recognition-low-resolution/data/english_decomposition.txt
      - KeepKeys:
          keep_keys: ['img_lr', 'img_hr', 'length', 'input_tensor', 'label']
  loader:
    shuffle: true
    batch_size_per_card: 22
    drop_last: True
    num_workers: 4

Eval:
  dataset:
    name: LMDBDataSetSR
    data_dir: /home/temp-user/workspace/plate-recognition-low-resolution/data/lmdb_sr/val_lmdb
    transforms:
      - SRResize:
          imgH: 48
          imgW: 320
          down_sample_scale: 1
      - SRLabelEncode:
          character_dict_path: /home/temp-user/workspace/plate-recognition-low-resolution/data/english_decomposition.txt
      - KeepKeys:
          keep_keys: ['img_lr', 'img_hr', 'length', 'input_tensor', 'label']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 16
    num_workers: 4
